controllers:
    resource: '../../src/Controller/'
    type: annotation
    prefix:
        en: '/en'
        fr: '/fr'
    requirements:
        _locale: 'en|fr'
    trailing_slash_on_root: false
    
kernel:
    resource: ../../src/Kernel.php
    type: annotation
