#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\HomeController::index
  prefix: /_locale

resetPasswordRequest:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request
  prefix: /_locale

sitemap:
  path: /sitemap
  controller: App\Controller\SitemapController::index
  prefix: /_locale